apiVersion: v1
kind: Service
metadata:
  name: blog-django-py
  namespace: foo
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: blog-django-py
  sessionAffinity: None
  type: ClusterIP
